# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qorF-DWUh7RQHvqtsR5JlcXjfdjhh_oz
"""

# Soddaroq Kalkulyator
def calculator():
    print("Welcome to Calculator!")
    print("Amallar:")
    print("1. Qo'shish (+)")
    print("2. Ayirish (-)")
    print("3. Ko'paytirish (*)")
    print("4. Bo'lish (/)")
    amal = input("Amalni tanlang (+, -, *, /): ")
    son1 = float(input("Birinchi sonni kiriting: "))
    son2 = float(input("Ikkinchi sonni kiriting: "))
    if amal == '+':
        natija = son1 + son2
    elif amal == '-':
        natija = son1 - son2
    elif amal == '*':
        natija = son1 * son2
    elif amal == '/':
        if son2 != 0:
            natija = son1 / son2
        else:
            return "Xato: Nolga bo‘lish mumkin emas!"
    else:
        return "Xato: Noto‘g‘ri amal tanlandi!"


    return f"Natija: {natija}"


print(calculator())